title: Yuri Furtado # your name (or website title) here
logo: "/images/1625241997811.jfif?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
Bachelor’s in Industrial Engineering, Certificate in Big Data Analytics and Microsoft Certified Data Analyst
Advanced knowledge using Excel, SQL and BI tools such Power BI and Tableau
Extensive experience in a multi-divisional environment as the key user for the ERP system
  <br><br>
  <a href="https://www.linkedin.com/in/ymello">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-JC69XBBS73 # your Google Analytics tracking ID here
